### PR TITLE
Implement a service that adds a secret key

### PR DESCRIPTION
**Pull request by RacingTadpole**
This would be required for any API calls that require a secret key to be added server-side. It is not needed yet, but I'd appreciate any feedback for when it is.

### CODE REVIEW

**Comment by kring** [comment]
I don't know much about the motivations for this feature, but one thing that jumps out at me is that anyone who runs a site on the proxy whitelist can trivially steal keys.  Just make a request to `/proxywithkey/keyiwanttosteal/http://mysite.gov.au` and the key shows up in mysite.gov.au's logs.

Why not associate keys with particular hosts or base URLs?  At that point it's pretty much the same as the proxyauth system we already have, it just passes the credentials differently.  We shouldn't need a separate service even.

**Comment by RacingTadpole** [comment]
That sounds like a better approach, thanks @kring. 

Here's a proposal then - we add to the proxy auth json a "parameters" key that adds to the URL parameters, eg.

```
{
    "www.some.remote.service.example.com": {
        "authorization": "Basic dGVzdHVzZXI6dGVzdHBhc3MK"
    },
    "some.other.service.example.com": {
        "parameters": [{
             key: "secret_key",
             value: "ABCDE12345"
         }, {
             key: "another_key",
             value: "XYZ"
         }]
}
``` 
Sound reasonable?  You could even have both types of authorization on the one endpoint if desired.

**Comment by kring** [comment]
Yep, sounds good to me!

**Comment by RacingTadpole** [comment]
I've now added a similar capability in #71.  It uses the approach you suggested to add custom headers, rather than custom query parameters.

**Pull request closed without merging**
