### PR TITLE
Fix bug in conversion stream handling.

### PR DESCRIPTION
**Pull request by stevage**
Still not 100% sure how to safely abort the stream. See http://stackoverflow.com/questions/38176369/how-to-safely-abort-a-piped-stream-in-nodejs

### CODE REVIEW

**Comment by kring** [comment]
A couple of observations:
* The size limit / abort isn't working at all because the callback passed to `response.on('data', ...)` never gets called.  I assume ogr2ogr is eating all the input so no one else can see it.
* The conversion service puts the uploaded file in `/tmp/upload_X` where `X` is some random identifier.  It doesn't remove it afterward, even if the conversion is successful.  I assume it is ogr2ogr doing this.

Given the two points above, perhaps we should manually manage create a temp file with the uploaded content so that we have better control over when to stop writing it and so that we can be sure to clean it up afterward.

**Comment by stevage** [comment]
Dammit. Hard to get both things working at once. There are middlewares that handle size restrictions, which I looked at using but they seemed like overkill. Now I'm not so sure.

**Comment by kring** [comment]
I don't think middleware will work either.  I think ogr2ogr is grabbing the data from the stream in such a way that node can't see it.

**Comment by stevage** [comment]
Only if the two streams are piped directly together. Probably attaching another stream in the middle would be enough.

**Comment by AlexGilleran** [comment]
Shouldn't you be wrapping `convertStream(response, req, res, hint)` in `if (!abort)` ?

**Comment by stevage** [comment]
>The conversion service puts the uploaded file in `/tmp/upload_X` where `X` is some random identifier.  It doesn't remove it afterward, even if the conversion is successful.  I assume it is ogr2ogr doing this.

I don't think that's ogr2ogr. Its temp directories start with `ogr_` and it deletes them afterwards.

```
var genTmpPath = exports.genTmpPath = function () {
  return path.join(tmpdir, 'ogr_'+(genInc++).toString(14))
}
```

**Comment by kring** [comment]
> Only if the two streams are piped directly together. Probably attaching another stream in the middle would be enough.

Yeah, I suspect that will work.  Even without middleware that should work I think.

> Shouldn't you be wrapping convertStream(response, req, res, hint) in if (!abort) ?

Not sure if I totally understand what you're asking.  We're basically trying to attach two things to the same request body stream: one is ogr2ogr to actually get the data and convert it, the other is our own thing that just adds up the size so far and aborts if it gets too big.

> I don't think that's ogr2ogr. Its temp directories start with ogr_ and it deletes them afterwards.

Hmm yeah the name `upload` implies something other than ogr2ogr, too.  Not at all obvious where it's coming from, but a new one appears in my tmp directory every time I upload a file.

**Comment by AlexGilleran** [comment]
> Not sure if I totally understand what you're asking. We're basically trying to attach two things to the same request body stream: one is ogr2ogr to actually get the data and convert it, the other is our own thing that just adds up the size so far and aborts if it gets too big.

So as far as I can tell you're already adding up the size and trying to abort but the abort isn't working (because that method doesn't really do anything meaningful). Before you checked that abort flag at the end to make sure the request hadn't been aborted, but that's gone now. If you put it back in but on the streaming event, it should give you the instant-abort-like behaviour you're seeking right? As in, it'll stop passing bytes through to ogr once the abort has happened.

**Comment by kring** [comment]
> So as far as I can tell you're already adding up the size and trying to abort but the abort isn't working 

No, the problem is that adding up the size isn't working, because the function that's supposed to receive data never does.  ogr eats it all.

**Comment by AlexGilleran** [comment]
Oh right, I thought the convertStream thing was in the data event for some reason, never mind.

**Pull request merged**
